package xuxin.j2ee.webservice.demo1.client.wsdl2java;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-12T15:20:04.475+08:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://server.demo1.webservice.j2ee.xuxin/", name = "IHelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectMaxLongNameStudent", targetNamespace = "http://server.demo1.webservice.j2ee.xuxin/", className = "xuxin.j2ee.webservice.demo1.client.wsdl2java.SelectMaxLongNameStudent")
    @WebMethod
    @ResponseWrapper(localName = "selectMaxLongNameStudentResponse", targetNamespace = "http://server.demo1.webservice.j2ee.xuxin/", className = "xuxin.j2ee.webservice.demo1.client.wsdl2java.SelectMaxLongNameStudentResponse")
    public xuxin.j2ee.webservice.demo1.client.wsdl2java.Student selectMaxLongNameStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        xuxin.j2ee.webservice.demo1.client.wsdl2java.Student arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        xuxin.j2ee.webservice.demo1.client.wsdl2java.Student arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectMaxAgeStudent", targetNamespace = "http://server.demo1.webservice.j2ee.xuxin/", className = "xuxin.j2ee.webservice.demo1.client.wsdl2java.SelectMaxAgeStudent")
    @WebMethod
    @ResponseWrapper(localName = "selectMaxAgeStudentResponse", targetNamespace = "http://server.demo1.webservice.j2ee.xuxin/", className = "xuxin.j2ee.webservice.demo1.client.wsdl2java.SelectMaxAgeStudentResponse")
    public xuxin.j2ee.webservice.demo1.client.wsdl2java.Student selectMaxAgeStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        xuxin.j2ee.webservice.demo1.client.wsdl2java.Student arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        xuxin.j2ee.webservice.demo1.client.wsdl2java.Student arg1
    );
}
